version: '3'
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    user: "1000"
    networks:
      - grafana_network
    depends_on:
      - influxdb
  influxdb:
    container_name: influxdb-container
    image: influxdb:1.8.3
    ports:
      - '8086:8086'
    networks:
      - grafana_network
    environment:
      - INFLUXDB_DB=workshop
      - INFLUXDB_USER=workshop
      - INFLUXDB_USER_PASSWORD=workshop
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin 
      - INFLUXDB_ADMIN_PASSWORD=admin
  mqtt:
      container_name: mqtt-container
      image: eclipse-mosquitto:1.6
      restart: always
      ports:
        - 1883:1883
networks:
  grafana_network: